### ISSUE TITLE
Questions about Gen_bin_cell_atac.R script

### ISSUE THREAD

**Issue by Ping-lin14** [seasoncloud/Alleloscope#1]
Hi

According to the Gen_bin_cell_atac.R script, when I execute `
if(grepl("chr",bin_bed[1,1])){
    bin_bed[,1]=gsub("chr","",bin_bed[,1])
  }else{
    bin_bed=bin_bed
  }
`, I receive an error`Error in if (grepl("chr", bin_bed[1, 1])) {: argument length is zero`. 

And when I execute `query=GRanges(paste0('chr',chr200k[,1]), IRanges(chr200k[,2]+1,chr200k[,3]))`, I receive an error`Error in stop_if_wrong_length(what, ans_len) : 
  'ranges' must have the length of the object to construct (1) or length 1`.
Is that right?

**Comment by seasoncloud** [comment]
Thanks for your interest in Alleloscope!
The error seems to be due to the bin_bed variable. The input for the bin_bed parameter should be " A matrix of the BED format. The first three columns are 'chr', "start site", "end site". Each row is a bin region." 
Could you try "head(bin_bed)" to see if it the format looks like the following example?
![image](https://user-images.githubusercontent.com/25533249/104939701-c0c7c100-597e-11eb-9e79-e5e0254ceb3c.png)

**Comment by Ping-lin14** [comment]
I found that I entered the wrong .bed file, and now the problem is solved.

I have another question. After I filter out the quality drop cells and SNP, the warning message `NA generated during the forced change` will be generated. Do you want to ignore it?

Since I only have scATAC data, so I used `Obj_filtered$seg_table <- Segmentation(Obj_filtered=Obj_filtered, 
                          raw_counts=raw_counts,
                          plot_seg = TRUE)` to generate the matrix for segmentation results from scDNA-seq.
However, the error message is generated `Error in strsplit(rownames(ref_counts), "-") : non-character argument`.
What is the treatment?

**Comment by seasoncloud** [comment]
To generate the bin by cell matrix using the Gen_bin_cell_atac.R file, I would like to note that the bed file is for the "fixed bins" not the peak regions with varying sizes. I added a helper function (https://github.com/seasoncloud/Basic_CNV_SNV/blob/main/scripts/Generate_bed.R) to help generate the bin_bed file based on your reference genome. 

The "Error in strsplit(rownames(ref_counts), "-") : non-character argument" resulted from no input for the ref_counts argument (which is required). 

The current Alleloscope version is developed for "scDNA-seq+ scATAC-seq" and "bulk DNA-seq + scATAC-seq". The current "Segmentation" function is developed for segmenting DNA sequencing data on the coverage (tumor+normal). We are planning to expand this to work on scATAC-seq data alone in the future.
