### ISSUE TITLE
Error in Est_regions

### ISSUE THREAD

**Issue by KatharinaSchmid** [seasoncloud/Alleloscope#10]
Hi,

thank you for developing Alleloscope, it is an interesting tool. We ran it successfully on our dataset, but we get problems when we filter less strict for the number of SNPs (nSNP=200 in the function Segments_filter). An error happens in the function Est_regions saying "number of cluster centres must lie between 1 and nrow(x)". This is the full output of the error message:

```
Estimation starts.
2:500001 No SNPs after filtering for 2:2000001 No SNPs after filtering for 2:2500001 2:3500001 No SNPs after filtering for 
2:5000001 No SNPs after filtering for 2:5500001 No SNPs after filtering for 2:6000001 No SNPs after filtering for 2:6500001 
2:7000001 No SNPs after filtering for 2:7500001 2:8000001 2:8500001 2:9000001 2:9500001 2:10000001 2:11000001 
2:11500001 2:12000001 No SNPs after filtering for 2:13000001 No SNPs after filtering for 2:14500001 2:15500001 No cells after 
filtering for 2:17000001 No SNPs after filtering for 2:18000001 2:19000001 2:19500001 2:20000001 2:20500001 No SNPs after 
filtering for 2:21000001 No SNPs after filtering for 2:23000001 No SNPs after filtering for 2:23500001 No SNPs after filtering for 
2:24500001 2:26000001 No SNPs after filtering for 2:26500001 2:27500001 2:28000001 2:28500001 No SNPs after filtering for 
2:29000001 No SNPs after filtering for 2:29500001 Fehler: number of cluster centres must lie between 1 and nrow(x)
```

Looking into the code, it is likely a problem of the kmeans function. Currently, regions are skipped with less than 3 SNPs left after filtering, but also for exactly 3 datapoints (SNPs) kmeans doesn't work for me, using R version 4.1.0. A toy example gives me:

```
> kmeans(c(1,2,3),centers=3)
Fehler: number of cluster centres must lie between 1 and nrow(x)
```

If I understood it correctly, it might be sufficient to change the filtering part in Est_regions to:
```
        if(dim(alt_all_sub)[1]<=3 | length(unique(af_all_sub))<=3){
          cat(paste0("No SNPs after filtering for ", chrr, " "))
          next
        }
```

It is in the end also a problem of our dataset being quite sparse, but I assume there is not really much more we can do here except choosing larger regions, I suppose?

Kind regards,
Katharina

**Comment by seasoncloud** [comment]
Hello Katharina,

Thanks for your interest in Alleloscope and helping debug for the extreme scenario! 
Your understanding is correct. It seems that the kmeans function does not allow setting the cluster number the same as the number of points. 
If you set ```if(dim(alt_all_sub)[1]<=3 | length(unique(af_all_sub))<=3){```, you'll probably filter out more regions but can bypass the error. 

And you are correct that if your dataset is sparse, detecting allele-specific CNAs in only larger regions will be more reliable. If you want to focus more on the subclone detection, you could play with the segmentation part-- trying different parameters to have more  smooth/longer segments for the downstream analysis. In this case, the CNAs you detect might not be that accurate (mixture of two or three CNA signals from multiple regions), but you can have more SNPs and lower variance for each region. This may still give you reasonable results for subclone detection. 

Hope this makes sense and let me know if you have other questions!

**Comment by KatharinaSchmid** [comment]
Thanks for the verification and the suggestions / explanations. I will play around with the segmentation length.
