### ISSUE TITLE
Final copy number states

### ISSUE THREAD

**Issue by marcjwilliams1** [seasoncloud/Alleloscope#3]
Hi, I have a couple of questions regarding the input/output of alleloscope.

1) What are the minimum requirements of the SNP vcf file? Is it just chr, position, ref, alt? Or does alleloscope use the other information. I can see in the example dataset there are many other fields in the vcf, are these all required?
2) Where is the assigned allele-specific copy number state for each segment in each cell stored? I found the genotype slot in the alleloscope object, what do these integers represent?

Thanks for your help!

**Comment by seasoncloud** [comment]
Hello, thanks for your interest in Alleloscope!

Please see the following for my answers.

1. Yes Alleloscope just required the four columns (chr, position, ref, alt) corresponding to column 1,2,4,5 in the typical vcf files. 
2. Thanks for bringing this up! I will put more description for the output. The numbers in "genotypes" correspond to the order of the figure legend in Fig. 2b and as attached. 
![image](https://user-images.githubusercontent.com/25533249/128737356-3acd76cd-415b-4366-a787-f2bd80ba9bc3.png)

Let me know if you have any question.

**Comment by marcjwilliams1** [comment]
Thank you for the quick reply.

**Comment by marcjwilliams1** [comment]
One more related question, in the example the genotypes go up to 24, but the image you posted above only goes up to 21. What are 22,23,24?

**Comment by seasoncloud** [comment]
The colors are just for visualization. Every haplotype profiles with the number of haplotypes>6 are all colored brown. Please see the following plot for the full information.

![image](https://user-images.githubusercontent.com/25533249/128754393-b8023cdc-49c4-412e-acb4-43baa63b5932.png)

**Comment by marcjwilliams1** [comment]
Thanks, so is 6 the maximum copy number state for a segment? Or is it just the plotting that's capped at 6?

**Comment by seasoncloud** [comment]
Yes the algorithm allows estimation of up to 6 copies for now.

**Comment by seasoncloud** [comment]
Thanks for bringing this up! Actually, we just added a parameter "maxcp" to allow the users to specify the maximum number of copies they want to detect. The number for the genotype estimation is not limited to 6 now, but the colors are still capped at 6 for cleaner visualization. Thanks for the suggestion!
