### ISSUE TITLE
scATAC data preprocess

### ISSUE THREAD

**Issue by wangruohan111** [seasoncloud/Alleloscope#6]
Hi, thanks for providing the package!

I find the peak-by-cell matrix from scATAC data should be regressed out by linear regression before the following analysis. Should I do the preprocessing before I use Alleloscope, or would Alleloscope conduct the process automatically? 

Thanks in any case!

**Comment by seasoncloud** [comment]
Hello,

Thanks for your interest in Alleloscope! Alleloscope focuses on the allele-specific copy number analysis (which does not require the pre-processing of the cell-by-bin matrix).

For the "scATAC-seq data analysis" section in the paper, it is for integrating the results from Alleloscope to the results from typical scATAC-seq peak analysis (Potential downstream analysis in [this page](https://github.com/seasoncloud/Alleloscope/tree/main/samples/SU008/scATAC)). You could choose any existing tools to perform the typical analysis like [Seurat](https://satijalab.org/signac/articles/pbmc_vignette.html) or [ArchR](https://www.archrproject.com/articles/Articles/tutorial.html).

Hope this helps!

**Comment by wangruohan111** [comment]
Got it. Thanks!
