### ISSUE TITLE
Can not download

### ISSUE THREAD

**Issue by silentFUSU** [seasoncloud/Alleloscope#7]
Thanks for providing such an interesting tool.
But I have some problem in downloading.
The problem is like this.
>devtools::install_github("seasoncloud/Alleloscope")
Downloading GitHub repo seasoncloud/Alleloscope@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
download from 'https://api.github.com/repos/seasoncloud/Alleloscope/tarball/HEAD' failed

**Comment by seasoncloud** [comment]
Hello,

Thanks for your interest in Alleloscope! I think github changed some setting recently. Could you try adding options(timeout=9999999) before running devtools::install_github("seasoncloud/Alleloscope") to see if it succeeds? So the code would be 

```
options(timeout=9999999)
devtools::install_github("seasoncloud/Alleloscope")
```

**Comment by silentFUSU** [comment]
!!!!That works, thank you very much for your answer!!!
