### ISSUE TITLE
The package can't be installed via devtools::install_github("seasoncloud/Alleloscope")

### ISSUE THREAD

**Issue by chupan1218** [seasoncloud/Alleloscope#8]
Hey Dr. Wu,

I would like to install your package on my local computer. But I got an error when I inputted this command line: devtools::install_github("seasoncloud/Alleloscope")
Downloading GitHub repo seasoncloud/Alleloscope@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/seasoncloud/Alleloscope/tarball/HEAD' failed

Please check it, thank you!

Best,
Chu

**Comment by seasoncloud** [comment]
Hello,

Thanks for your interest in Alleloscope! Could you try adding one line
```options(timeout=9999999)``` before running ```devtools::install_github("seasoncloud/Alleloscope")``` and see if it works. Thanks!

**Comment by chupan1218** [comment]
Cool!!! It works! Thank you!
